# Generated by Django 4.2.15 on 2024-08-24 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(choices=[('happy', 'Happy'), ('normal', 'Normal'), ('sad', 'Sad')], default='normal')),
                ('day_description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('grateful_for', models.TextField(blank=True)),
                ('improve_on', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
