# Generated by Django 4.2.15 on 2024-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('normal', 'Normal'), ('sad', 'Sad')], default='normal', max_length=10),
        ),
    ]
