# Generated by Django 4.2.15 on 2024-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journalentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='day_description',
            field=models.CharField(max_length=65),
        ),
    ]
